### ISSUE TITLE
Readline and Tokenize

### ISSUE THREAD

**Issue by carologata** [bbazaglia/42-minishell#3]
Implement readline and tokenize.

**Comment by bbazaglia** [comment]
commit 5d2c7f242fa1767c4082f4c3bee0ea405ab17e85 (HEAD -> dev, origin/dev)
Author: Beatriz <bbazagli@student.42sp.org.br>
Date:   Mon Mar 4 14:55:58 2024 -0300

    d0: tokenize and readline all set for merging with the main branch
